### ISSUE TITLE
Android低版本无法使用

### ISSUE THREAD

**Issue by shoulderdh** [DLTech21/ofd.android#1]
use a compatible library with a minSdk of at most 19,
![image](https://user-images.githubusercontent.com/14287365/146770608-b0794403-d5f9-41c4-8071-ffad732e8514.png)

**Comment by DLTech21** [comment]
低版本需要私信

**Comment by shoulderdh** [comment]
> 

发邮件了  帮忙看看 谢谢

**Comment by DLTech21** [comment]
已支持低版本

**Comment by shijianhub** [comment]
新的aar混淆了ofd转pdf.能放开这个混淆api.邮寄3057562424@qq.com麻烦了
