### ISSUE TITLE
水印问题

### ISSUE THREAD

**Issue by w9623** [DLTech21/ofd.android#2]
能自行设置水印吗

**Comment by DLTech21** [comment]
能，加微信私聊

**Comment by w9623** [comment]
w962311755



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Donal ***@***.***&gt;
发送时间: 2022年2月25日 16:35
收件人: DLTech21/ofd.android ***@***.***&gt;
抄送: w9623 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [DLTech21/ofd.android] 水印问题 (Issue #2)





 
能，加微信私聊
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jaxyzn** [comment]
> 能自行设置水印吗

你好，我想请问一下使用IDEAclone代码后应该如何导入呢？我这边clone下来后感觉不想是安卓项目，也没办法安装虚拟器进行模拟？

**Comment by w9623** [comment]
> > 可以自己设置水印吗
> 
> 你好，我应该想问一下使用IDEAclone代码后如何导入呢？

**Comment by w9623** [comment]
> > 可以自己设置水印吗
> 
> 你好，我应该想问一下使用IDEAclone代码后如何导入呢？

我是用Android studio导入的，idea不太清楚

**Comment by DLTech21** [comment]
一般用Android studio比较合适

**Comment by focuseyes360** [comment]
水印问题怎么设置呢？另外我想修改ui

**Comment by DLTech21** [comment]
> 水印问题怎么设置呢？另外我想修改ui

加微信

**Comment by DLTech21** [comment]
已去
